from gturtle import *

makeTurtle()
hideTurtle()
def square():
    for i in range(4):
        forward(50)
        right(90)
    forward(50)
    right(90)
    forward(50)
    left(90)
right(45)
setPenColor("red")
setFillColor("red")
startPath()
square()
fillPath()
setPenColor("green")
setFillColor("green")
startPath()
square()
fillPath()
setPenColor("blue")
setFillColor("blue")
startPath()
square()
fillPath()
setPenColor("black")
setFillColor("black")
startPath()
square()
fillPath()
